create add  account
withmoney/withmoney-web pull request #119
Opened 2021-01-25 22:35 UTC by diegocosta-dev

2021-01-25 23:25 UTC, davidcostadev requested changes

2021-01-25 23:25 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +          <Text>Action</Text>
Could you please include the Currency column as well?

2021-01-25 23:25 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +        </Content>
Please include a placeholder container while is loading and please include this to show errors as well:
`{error && <Alert isDanger>{error.message}</Alert>}`

2021-01-25 23:25 UTC, davidcostadev commented on src/pages/Dashboard/NavBar/Menu.tsx
> +        <ButtonLink onClick={() => menuIsOpen(false)} to="/accounts">
those functions are duplicated, please create just a function for it

2021-01-25 23:25 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/AddAccount/index.tsx
> +                  onChange={(e) => setAccountName({ ...form, accountCurrency: e.target.value })}
Why not we are not using the handleInput? on here?

2021-01-25 23:25 UTC, davidcostadev commented on src/schema/checkField.ts
> +  accountName: yup.string().required('Required'),
We need to have field for currency as well

2021-01-27 16:32 UTC, davidcostadev requested changes

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +                  <option value="">Select you currency</option>
```suggestion
                  <option value="">Select your currency</option>
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/AddAccount/index.tsx
> +                  <option>Select you currency</option>
```suggestion
                  <option>Select your currency</option>
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/AddAccount/index.tsx
> +              Create Account
Please put Creating... and a spinner when the mutation is loading

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +export default AddAccount;
```suggestion
export default UpdateAccount;
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +const AddAccount = () => {
```suggestion
const UpdateAccount = () => {
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/AddAccount/index.tsx
> +const PageHeader = styled.div`
There duplicated code on those styled, let's create a component for it, or use it as style.ts file

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +  const { data } = useAccounts();
Instead of use `useAccounts` we need to have another to use 
```graphql
findUniqueAccount(
where: AccountWhereUniqueInput
): Account
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +    accountCurrency: account?.currency,
It's not a good idea use the useState the optional object, if the object its undertined so our state will be undefined, it's better to use useEffect to get the updated value after fetch

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +          <Form onSubmit={handleUpdateAccount}>
We should use a placeholder component to be showing when we getting the current account. To show whe the loading is true

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +      deleteAccount({ variables: { id: selectedAccount?.id } });
to use it on the right way we need to put the `await` on front of the `deleteAccount`

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +      restoreAccount({ variables: { id: selectedAccount?.id } });
Please put `await` here.

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +        {error && toast.error(error.message)}
It's not a good idea use toast.error for queries, let's use `<Alert />` instead, and `toast.error` is a javascript function and not a react component.

2021-01-27 16:32 UTC, davidcostadev commented on src/modals/DeleteModal.tsx
> +  handleDelete: () => void;
As this is a vent, let's call it as `onDelete`

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +                  <ButtonLink
We should allow the user to edit the current operation

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/index.tsx
> +            <Route path="/createAccount" component={AddAccount} />
```suggestion
            <Route path="/accounts/new" component={AddAccount} />
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/index.tsx
> +            <Route path="/updateAccount/:id" component={UpdateAccount} />
```suggestion
            <Route path="/accounts/edit/:id" component={UpdateAccount} />
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/AddAccount/index.tsx
> +                ></Input>
If we don't need a children so we should use the A closetag
```suggestion
                />
```

2021-01-27 16:32 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +                ></Input>
```suggestion
                />
```

2021-01-27 16:32 UTC, davidcostadev commented on src/modals/DeleteModal.tsx
> +  handleDelete: () => void;
or `onConfirm` so we could use this modal to another objective

2021-01-27 18:48 UTC, diegocosta-dev commented on src/pages/Dashboard/index.tsx
> +            <Route path="/createAccount" component={AddAccount} />
I don't know why this don't work, I'm using  "accounts-new"  and "accounts-edit"

2021-01-27 18:55 UTC, diegocosta-dev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +          <Form onSubmit={handleUpdateAccount}>
I don't understand this thing

2021-01-27 19:07 UTC, davidcostadev requested changes

2021-01-27 19:07 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/UpdateAccount/index.tsx
> +          {error && window.alert(error.message)}
src/components/Alert.tsx here too

2021-01-27 19:07 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +                  </ButtonLink>
The way that I thought is more the edit out of this inline condition so we could avoid duplications

2021-01-27 19:07 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +                    disabled={loading}
The simple way is just to use `disabled={loading || account.id === currentAccountId}` :boom:

2021-01-27 19:07 UTC, davidcostadev commented on src/pages/Dashboard/Accounts/index.tsx
> +        {error && window.alert(error.message)}
Lets use `components/Alert` instead

2021-01-27 20:21 UTC, davidcostadev approved these changes

2021-01-27 20:21 UTC, merged