chore variant-buttons#53
withmoney/withmoney-web pull request #59
Opened 2020-12-08 20:28 UTC by diegocosta-dev

2020-12-09 01:25 UTC, davidcostadev requested changes

2020-12-10 13:24 UTC, davidcostadev requested changes

2020-12-10 13:24 UTC, davidcostadev commented on package.json
> +    "css-variables": "^0.1.7",
This is not needed you can remove it

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +    box-shadow: 0px 0px 0px 2px
0px -> 0

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +    border: solid 2px
border-color: {color}

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +  rouded?: boolean;
typo: rouded -> rounded

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +type TextProps = {
ButtonProps or Props

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +    border: solid 2px
border-color: {color}

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +    border: solid 2px
border-color: {color}

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +  border: solid 2px ${({ variation = 'default' }) => `var(--button-border-${variation})`};
border: {width} {style} {color}

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +  padding: 11px 13px;
Please use pair numbers

2020-12-10 13:24 UTC, davidcostadev commented on src/components/Button.tsx
> +  font-size: 16px;
Please use vars on font-sizes

2020-12-10 13:29 UTC, gustavoFreireS approved these changes

2020-12-10 16:22 UTC, davidcostadev approved these changes

2020-12-10 16:23 UTC, merged