Feacture Textarea-component
withmoney/withmoney-web pull request #71
Opened 2020-12-11 19:43 UTC by diegocosta-dev

resolves #69

2020-12-11 19:52 UTC, davidcostadev requested changes

2020-12-11 19:52 UTC, davidcostadev commented on src/components/Textarea.tsx
> +  padding: var(--text-area-box-shadow-padding-top) var(--text-area-box-shadow-padding-left);
padding: var(--text-area-box-shadow-padding-top) var(--text-area-box-shadow-padding-left); 
-> 
  padding: var(--text-area-padding-vertical) var(--text-area-padding-horizontal);

2020-12-14 12:14 UTC, gustavoFreireS requested changes

2020-12-14 12:14 UTC, gustavoFreireS commented on src/components/Textarea.tsx
> +  ::-webkit-input-placeholder {
remember to include other browsers as well: https://css-tricks.com/almanac/selectors/p/placeholder/

2020-12-14 14:15 UTC, davidcostadev approved these changes

2020-12-14 14:23 UTC, merged