Feacture page sign up
withmoney/withmoney-web pull request #78
Opened 2020-12-16 00:51 UTC by diegocosta-dev

Resolves #73

2020-12-16 23:13 UTC, davidcostadev requested changes

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +                style={{ width: '95%', marginRight: '10px' }}
this width: '95%' don't make sense to me

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +    setFormIsValid(!isValid);
this don't make anysense to me, isValid should be true, and why the `!`?

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +    passwordConfirm: '',
Please create a value called, 
```
const initialValue = {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    passwordConfirm: '',
}

and use it on useState(initialValue)

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +              style={{ marginBottom: '0px', marginRight: '20px' }}
I don't really like to use those custom style, please find a why to use it inside of the Input instead

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +              {loading ? 'Sending...' : 'Register'}
Registering

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +            <Button disabled={formIsValid} style={{ margin: 'auto' }} variation="primary">
Please remove this margin, and put a prop on flex called justifyContent="center" to work

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +      <Container show={!successMessage}>
Let use {successMessage && ...} or {!successMessage && ... } instead

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/mutations/CheckHash.ts
> +export default CHECK_HASH;
instead of creating a folder called mutations, let's create this structure

src/graphql/AuthGql.js and use 

`export const CHECK_HASH = gql` instead of `export default`

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/mutations/register.ts
> +const USER_REGISTER = gql`
Move this mutation to `src/graphql/AuthGql.js`

2020-12-16 23:13 UTC, davidcostadev commented on src/pages/validations/useValidation.ts
> +});
please move this `src/schema/registration.ts` instead

2020-12-16 23:13 UTC, davidcostadev commented on src/routes.tsx
> +import RegistrationVerify from './pages/RegistrationVerify';
Please fix the ordering of the imports

2020-12-16 23:13 UTC, davidcostadev commented on src/routes.tsx
> +        <Route path="/signup" component={SignUp} />
This Route is duplicated

2020-12-16 23:13 UTC, davidcostadev commented on src/routes.tsx
> +        <Route path="/" exact component={Login} />
We will need use another page from home, but for not, lets use it instead
```
        <Redirect exact from="/" to="/signin" />
        <Route path="/signin" exact component={Login} />
```

2020-12-16 23:13 UTC, davidcostadev commented on src/theme.ts
> +    --input-margin-bottom: 0;
Please Create a component Called InputGroup and move this margin to there, this is the solution

2020-12-17 16:42 UTC, diegocosta-dev commented on src/pages/SignUp.tsx
> +                style={{ width: '95%', marginRight: '10px' }}
this is the way that I used to separate the inputs fields, "first name" and "ast name"

2020-12-17 19:12 UTC, davidcostadev requested changes

2020-12-17 19:12 UTC, davidcostadev commented on package.json
> +    "@apollo/client": "^3.2.7",
"@apollo/client": "^3.2.7",
    "@apollo/react-hooks": "4.0.0",
    "@apollo/react-testing": "4.0.0",
    "@styled-icons/entypo": "^10.18.0",
    
    This packages need to be on dependencies instead of devDependencies

2020-12-17 19:12 UTC, davidcostadev commented on src/components/Flex.tsx
> +  align?: 'center' | 'flex-end' | 'space-between' | 'space-around';
It's missing flex-start and space-evenly

2020-12-17 19:12 UTC, davidcostadev commented on src/pages/RegistrationVerify.tsx
> +              <Text style={{ margin: '10px' }} variation="primary" align="center">
please your margin prop instead of style

2020-12-17 19:12 UTC, davidcostadev commented on src/pages/RegistrationVerify.tsx
> +            <Text variation="danger" align="center">
Let's the Alert component instead

2020-12-17 19:12 UTC, davidcostadev commented on src/pages/SignUp.tsx
> +      } catch (err) {}
You don't fix this one

2020-12-17 19:12 UTC, davidcostadev commented on src/routes.tsx
> +        <Route path="/signin" exact component={Login} />
please remove this exact from this Route

2020-12-17 20:54 UTC, diegocosta-dev commented on src/pages/SignUp.tsx
> +      } catch (err) {}
I puted inside of useEffect

2020-12-17 22:58 UTC, gustavoFreireS requested changes

2020-12-17 22:58 UTC, gustavoFreireS commented on src/components/Container.tsx
> +const Container = styled.div`
alongside with setting the paddings a good practice is to set the `max-width` of the container two (this way it will not scale all the way up on bigger screens), something like `1024px` is enough

2020-12-17 22:58 UTC, gustavoFreireS commented on src/components/Input.tsx
> +  width: 100%;
I think a good prop to add here is `size` because at least for me I aways have to use three kinds of text inputs when dealing with forms: `half-size` inputs that on a single line I can have two inputs, `small-size` inputs for example in the case of addresses that I can have neighborhood, number and street name and `full-size` ones that I use when it is a single input on a line

2020-12-17 22:58 UTC, gustavoFreireS commented on src/components/LoadingSpiner.tsx
> +      transform: translate3d(-50%, -50%, 0) rotate(0deg);
why not just use the `transform: rotate()` ? it will ensure 60 fps

2020-12-17 22:58 UTC, gustavoFreireS commented on src/components/LoadingSpiner.tsx
> +    animation-play-state: inherit;
no need to set this

2020-12-17 22:58 UTC, gustavoFreireS commented on src/pages/SignUp.tsx
> +      } catch (err) {}
you have to put the error inside the `catch` block to ensure it's fired on the right time  putting it on `usEffect` could cause some unexpected side-effects, also it's easier to test in the future

2020-12-18 14:58 UTC, diegocosta-dev commented on src/components/LoadingSpiner.tsx
> +      transform: translate3d(-50%, -50%, 0) rotate(0deg);
I don't understanded this

2020-12-18 17:02 UTC, davidcostadev commented on src/components/Container.tsx
> +const Container = styled.div`
We don't need this

2020-12-18 17:08 UTC, davidcostadev commented on src/components/Input.tsx
> +  width: 100%;
Our input will always get the full size

2020-12-18 17:09 UTC, davidcostadev approved these changes

2020-12-18 17:10 UTC, merged