Reset password page
withmoney/withmoney-web pull request #81
Opened 2020-12-18 16:49 UTC by diegocosta-dev

resolver #79

2020-12-18 17:18 UTC, gustavoFreireS requested changes

2020-12-18 17:18 UTC, gustavoFreireS commented on src/pages/ResetPassword.tsx
> +  const [formError, setFormError] = useState('');
it would be better to have a single object here to set the form state, for example:
```javascript
const [formState, setFormState] = {
  error: false,
  valid: false
}
```

2020-12-18 17:18 UTC, gustavoFreireS commented on src/pages/SignUp.tsx
> +  const [form, setForm] = useState(initialValues);
same thing here as the last comment

2020-12-18 17:18 UTC, gustavoFreireS commented on src/schema/registration.ts
> +        /* @ts-ignore */
I see

2020-12-18 17:25 UTC, davidcostadev commented on src/schema/registration.ts
> +        /* @ts-ignore */
It was needed

2020-12-18 17:25 UTC, davidcostadev approved these changes

2020-12-18 20:01 UTC, davidcostadev requested changes

2020-12-18 20:01 UTC, davidcostadev commented on src/pages/ResetPassword.tsx
> +  const [email, setEmail] = useState({ email: '' });
please call it as form instead of email

2020-12-18 20:01 UTC, davidcostadev commented on src/pages/SignUp.tsx
>  const SingUp = () => {
SingUp -> SignUp

2020-12-18 20:01 UTC, davidcostadev commented on src/routes.tsx
> +        <Route path="/reset-password" component={ChangePassword} />
let's call it as change-password

2020-12-18 23:04 UTC, diegocosta-dev commented on src/routes.tsx
> +        <Route path="/reset-password" component={ChangePassword} />
the api redirect to /change-password

2020-12-18 23:19 UTC, diegocosta-dev commented on src/routes.tsx
> +        <Route path="/reset-password" component={ChangePassword} />
the api redirect us to this URL "reset-password?hash=8884455655"

2020-12-19 00:42 UTC, gustavoFreireS approved these changes

2020-12-19 00:44 UTC, davidcostadev approved these changes

2020-12-19 00:44 UTC, merged