Feature dashboard side bar
withmoney/withmoney-web pull request #89
Opened 2020-12-22 23:01 UTC by diegocosta-dev

resolves #86

2020-12-23 17:46 UTC, davidcostadev requested changes
create a file called currency on utils and put those functions there:

```js
export function currencyFormat(lang, currency, number) {
  return new Intl.NumberFormat(lang, { style: 'currency', currency }).format(number);
}

export function currencyReverseFormatString(lang, currency, money) {
  const separatorDecimal = new Intl.NumberFormat(lang, {
    style: 'decimal'
  })
    .format(11.11)
    .replace(/\d/g, '');

  const separatorThousands = new Intl.NumberFormat(lang, {
    style: 'decimal'
  })
    .format(1111)
    .replace(/\d/g, '');

  const symbolOnLeft = new Intl.NumberFormat(lang, {
    style: 'currency',
    currency
  })
    .format(1)
    .replace(new RegExp(`\\d|[${separatorDecimal}${separatorThousands}]*`, 'g'), '');

  const stringNumber = money
    .replace(new RegExp(`[${separatorThousands}]`, 'g'), '')
    .replace(separatorDecimal, '.')
    .replace(new RegExp(`[${symbolOnLeft}]`, 'g'), '');
  return stringNumber;
}

export function currencyReverseFormat(lang, currency, money) {
  return parseFloat(currencyReverseFormatString(lang, currency, money));
}


export const inputCurrencyFormat = value => {
  if (value.length) {
    const valueStr = value.replace(/[^0-9]/g, '').padStart(3, '0');

    if (Number.isNaN(parseInt(valueStr, 10))) {
      return 0;
    }

    return parseFloat([valueStr.substr(0, valueStr.length - 2), valueStr.substr(-2)].join('.'));
  }

  return 0;
};
```

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/NavBar/index.tsx
> +  max-height: 50px;
let's just use height: instead of use min and max

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/NavBar/index.tsx
> +  width: 100%;
This property is not needed

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Balance.tsx
> +      <Text>R$ 1200,00</Text>
Let's use `currencyFormat(LANG, CURRENCY, 1200)`

create a file called `src/constants/currency` and put
```js
export const LANG = 'pt-BR'
export const CURRENCY = 'BRL'
```

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Balance.tsx
> +  border-bottom: solid 2px #f2f2f2;
please use this instead `2px solid #f2f2f2`

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/HamburgerMenu.tsx
> +      <Menu title="Withmoney" />
Withmoney -> withmoney

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/HamburgerMenu.tsx
> +const Menu = styled(Icon)`
MenuIcon

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/HamburgerMenu.tsx
> +  border-right: solid 2px #f2f2f2;
please use this instead 2px solid #f2f2f2

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Info.tsx
> +        <Text>R$ {current}</Text>
please use the currencyFormat function here

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Information.tsx
> +      <Info percent="80%" color="#80DA89" name="Entrance" current="100" desired="110" />
Instead of use percent here, lets convert current and desired to numbers and make this calculation inside of component

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Information.tsx
> +  border-bottom: solid 2px #f2f2f2;
width style color

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/ResourcesList.tsx
> +      <Resource active>
This need to use <Link /> instead of div

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/ResourcesList.tsx
> +const ResourcesList = () => {
Please call this component Menu

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/ResourcesList.tsx
> +  width: 300px;
this is not needed

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Info.tsx
> +  percent?: string;
Please remove all those `?` it should be required

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Info.tsx
> +  width: 100%;
remove this

2020-12-23 17:46 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Info.tsx
> +  width: 100%;
remove this

2020-12-28 15:15 UTC, diegocosta-dev commented on src/pages/Dashboard/SideBar/Information.tsx
> +  border-bottom: solid 2px #f2f2f2;
I don't understand this

2020-12-28 17:28 UTC, davidcostadev approved these changes

2020-12-28 17:28 UTC, merged