Feature operations component
withmoney/withmoney-web pull request #97
Opened 2021-01-04 13:33 UTC by diegocosta-dev

resolves #93

2021-01-04 14:32 UTC, davidcostadev requested changes

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Dashboard/Operations/ContentPage.tsx
> +      <Route path="/unforeseen" component={Unforeseen} />
```suggestion
```

We are not going to use those routes

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Dashboard/SideBar/Menu.tsx
> +          setActiveDashboard(true);
instead of doing a state of each of menu, lets use
setActiveMenu('dashboard') for onClick and isActive={activeMenu === 'dashboard'} it allow us to include more menus if it's needed

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Components/Buttons.tsx
> +      <Button open={activeButton === 'Entrance'} to="/dashboard">
Instead of use Link, let store the active Tab on state, `onClick={setCurrentTransactionType}`

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Components/Buttons.tsx
> +export const Buttons = ({ activeButton }: Props) => {
Let's call it as Tabs instead of buttons

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Components/Container.tsx
> +import styled from 'styled-components';
Please move this file to a style folder

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Components/Table.tsx
> +`;
instead of use export of each component lets use static components Like

Table.Header = THeader
Table.Body = TBody
Table.Foot = TFoot
Table.Row = TH
Table.Cell = TD

and so use can use
```jsx
<Table>
   <Table.Header>
   <Table.Body>
      <Table.Row>
         <Table.Cell>

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Entrance/EntranceButton.tsx
> +};
I don't think that this component should be alone, move this to the parent component instead

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Entrance/EntranceData.tsx
> +    price: 'R$ 12,00',
Please use float instead, and use the format function

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Entrance/EntranceData.tsx
> +      {data &&
let use `!!data.length` instead

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Entrance/EntranceInfo.tsx
> +const InfoContainer = styled.div`
FooterContainer

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Entrance/EntranceLoad.tsx
> +const EntranceLoad = () => {
TransactionPlaceholder

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Entrance/EntranceLoad.tsx
> +const Box = styled.div`
Call is as CellPlaceholder

2021-01-04 14:32 UTC, davidcostadev commented on src/pages/Transactions/Entrance/index.tsx
> +          <EntranceTitle />
Let use Operation word instead of Entrance

2021-01-04 17:07 UTC, diegocosta-dev commented on src/pages/Transactions/Components/Table.tsx
> +export default { Table, Header, Body, Foot, Row, Cell, Config };
I don't know how to do this

2021-01-05 14:30 UTC, davidcostadev approved these changes

2021-01-05 14:31 UTC, merged